Remove thread creation in `PacketReader::unInject`
CodingAir/CodingAPI pull request #24
Opened 2023-02-03 17:35 UTC by Kamillaova

Creating a new thread on every player leave, for what?

..maybe a better solution is to use `channel.eventLoop().execute(runnable)` ?

2023-02-05 23:26 UTC, erikzimmermann commented
I'm pretty sure I added this since doing it asynchonously crashed the server sometimes...
Not 100% sure but yeah, I see the point that this is quite ugly :D

However, this code ran on a pretty big server without any issues so I don't really wanna touch that. Is this tested?

2023-02-06 04:59 UTC, Kamillaova commented
> Is this tested

with dumb bot attack (500 bots) - yes
also..

https://github.com/DecentSoftware-eu/DecentHolograms/blob/8ab5cb4bf37b645f9b7e9821eeabccb4b6c58b9e/src/main/java/eu/decentsoftware/holograms/api/nms/PacketListener.java#L64
https://github.com/DecentSoftware-eu/DecentHolograms/blob/8ab5cb4bf37b645f9b7e9821eeabccb4b6c58b9e/src/main/java/eu/decentsoftware/holograms/api/player/PlayerListener.java#L33
- does it in the server thread

https://github.com/filoghost/HolographicDisplays/blob/70779348af6870d711a5ad322ffe47aec981397b/nms/v1_16_r3/src/main/java/me/filoghost/holographicdisplays/nms/v1_16_R3/VersionNMSManager.java#L99
- does in in the channel eventloop


> I see the point that this is quite ugly

I was horrified after I added the thread creation logs :>

2023-02-19 10:42 UTC, erikzimmermann requested changes

2023-02-19 10:42 UTC, erikzimmermann commented on src/main/java/de/codingair/codingapi/player/data/PacketReader.java
> +        if (later != null) Bukkit.getScheduler().runTask(plugin, later);
Please first check if the plugin is still enabled. Otherwise, we would get an error every time we disable the plugin.

2023-02-19 10:42 UTC, erikzimmermann commented on src/main/java/de/codingair/codingapi/player/data/PacketReader.java
> +        }
Please do this in an executor as mentioned in your comment that pointed to [HolographicDisplays](https://github.com/filoghost/HolographicDisplays/blob/70779348af6870d711a5ad322ffe47aec981397b/nms/v1_16_r3/src/main/java/me/filoghost/holographicdisplays/nms/v1_16_R3/VersionNMSManager.java#L99).

2023-04-12 09:50 UTC, closed without merging